# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in
# linters documentation

# all, none, or list of linter keys
APPLY_FIXES: all

# If you use ENABLE variable, all other languages/formats/tooling-formats will
# be disabled by default
# ENABLE:

# If you use ENABLE_LINTERS variable, all other linters will be disabled by
# default
# ENABLE_LINTERS:

DISABLE_LINTERS:
  - SPELL_CSPELL
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_TRIVY
  - REPOSITORY_SYFT
  - REPOSITORY_GRYPE
  - COPYPASTE_JSCPD
  - REPOSITORY_KICS
  - SPELL_LYCHEE
  - REPOSITORY_DEVSKIM
SHOW_ELAPSED_TIME: true

# Uncomment if you want MegaLinter to detect errors but not block CI to pass
# DISABLE_ERRORS: true
GITHUB_COMMENT_REPORTER: true
GITHUB_STATUS_REPORTER: true
VALIDATE_ALL_CODEBASE: true
OUTPUT_DETAIL: detailed
# Disable Line Length on markdown files and reenable markdown lint rules
MARKDOWN_MARKDOWNLINT_ARGUMENTS:
  - --disable
  - MD013
  # - --enable MD04 MD007 MD026 MD029 MD033 MD036
# # TODO: Fix the above megalinter command
