[package]
name = "ap33772s-rs"
version = "0.1.0"
edition = "2024"

[features]
default = ["sync"]
sync = ["dep:embedded-hal", "maybe-async/is_sync"]
async = ["dep:embedded-hal-async"]

[dependencies]
embedded-hal = {version="1.0.0", optional =true}
embedded-hal-async = {version ="1.0.0", optional = true}
maybe-async = "0.2.10"


[dev-dependencies]
ftdi = "0.1.3"
ftdi-embedded-hal = { version = "0.23.0", features = [
    "libftd2xx",
    "libftd2xx-static",
] }