#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Command {
    Status = 0x01,
    InterruptEnableMask = 0x02,
    OperationMode = 0x03,
    SystemConfiguration = 0x04,
    PowerDeliveryConfiguration = 0x05,
    SystemControl = 0x06,
    ThermalResistance25 = 0x0C,
    ThermalResistance50 = 0x0D,
    ThermalResistance75 = 0x0E,
    ThermalResistance100 = 0x0F,
    Voltage = 0x11,
    Current = 0x12,
    Temperature = 0x13,
    RequestedVoltage = 0x14,
    RequestedCurrent = 0x15,
    MinimumSelectionVoltage = 0x16,
    UnderVoltageProtectionThreshold = 0x17,
    OverVoltageProtectionThreshold = 0x18,
    OverCurrentProtectionThreshold = 0x19,
    OverTemperatureProtectionThreshold = 0x1A,
    DeratingThreshold = 0x1B,
    AllSourceStandardPowerRange = 0x20,
    SourceStandardPowerRange1 = 0x21,
    SourceStandardPowerRange2 = 0x22,
    SourceStandardPowerRange3 = 0x23,
    SourceStandardPowerRange4 = 0x24,
    SourceStandardPowerRange5 = 0x25,
    SourceStandardPowerRange6 = 0x26,
    SourceStandardPowerRange7 = 0x27,
    SourceExtendedPowerRange8 = 0x28,
    SourceExtendedPowerRange9 = 0x29,
    SourceExtendedPowerRange10 = 0x2A,
    SourceExtendedPowerRange11 = 0x2B,
    SourceExtendedPowerRange12 = 0x2C,
    SourceExtendedPowerRange13 = 0x2D,
    PowerDeliveryRequestMessage = 0x31,
    PowerDeliveryCommandMessage = 0x32,
    PowerDeliveryMessageResponse = 0x33,
}